asgardeo/asgardeo-java-oidc-sdk

.gitignore
io.asgardio.java.oidc.sdk/pom.xml
io.asgardio.java.oidc.sdk/src/main/java/io/asgardio/java/oidc/sdk/OIDCManager.java
io.asgardio.java.oidc.sdk/src/main/java/io/asgardio/java/oidc/sdk/OIDCManagerImpl.java
io.asgardio.java.oidc.sdk/src/main/java/io/asgardio/java/oidc/sdk/SSOAgentConstants.java
io.asgardio.java.oidc.sdk/src/main/java/io/asgardio/java/oidc/sdk/bean/AuthenticationInfo.java
io.asgardio.java.oidc.sdk/src/main/java/io/asgardio/java/oidc/sdk/bean/User.java
io.asgardio.java.oidc.sdk/src/main/java/io/asgardio/java/oidc/sdk/config/FileBasedOIDCConfigProvider.java
io.asgardio.java.oidc.sdk/src/main/java/io/asgardio/java/oidc/sdk/config/OIDCConfigProvider.java
io.asgardio.java.oidc.sdk/src/main/java/io/asgardio/java/oidc/sdk/config/model/OIDCAgentConfig.java
io.asgardio.java.oidc.sdk/src/main/java/io/asgardio/java/oidc/sdk/exception/SSOAgentClientException.java
io.asgardio.java.oidc.sdk/src/main/java/io/asgardio/java/oidc/sdk/exception/SSOAgentException.java
io.asgardio.java.oidc.sdk/src/main/java/io/asgardio/java/oidc/sdk/exception/SSOAgentServerException.java
io.asgardio.java.oidc.sdk/src/main/java/io/asgardio/java/oidc/sdk/request/OIDCRequestBuilder.java
io.asgardio.java.oidc.sdk/src/main/java/io/asgardio/java/oidc/sdk/request/OIDCRequestResolver.java
io.asgardio.java.oidc.sdk/src/test/java/io/asgardio/java/oidc/sdk/OIDCManagerImplTest.java
io.asgardio.java.oidc.sdk/src/test/java/io/asgardio/java/oidc/sdk/bean/AuthenticationInfoTest.java
io.asgardio.java.oidc.sdk/src/test/java/io/asgardio/java/oidc/sdk/bean/UserTest.java
io.asgardio.java.oidc.sdk/src/test/java/io/asgardio/java/oidc/sdk/config/FileBasedOIDCConfigProviderTest.java
io.asgardio.java.oidc.sdk/src/test/java/io/asgardio/java/oidc/sdk/config/model/OIDCAgentConfigTest.java
io.asgardio.java.oidc.sdk/src/test/java/io/asgardio/java/oidc/sdk/request/OIDCRequestBuilderTest.java
io.asgardio.java.oidc.sdk/src/test/java/io/asgardio/java/oidc/sdk/request/OIDCRequestResolverTest.java
io.asgardio.java.oidc.sdk/src/test/resources/oidc-sample-app.properties
io.asgardio.java.oidc.sdk/src/test/resources/testng.xml
pom.xml

Add new module, **asgardio.io.java.oidc.sdk**

Add OIDC SDK for Java

---

README.md
io.asgardio.java.oidc.sdk/pom.xml
pom.xml

Can be merged once #13 is merged.

Resolve comments in #13

---

README.md

Update java oidc sdk documentation
Related to : https://github.com/wso2/product-is/issues/9943

Update java oidc sdk documentation

---

io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/DefaultOIDCManager.java

$subject.
Fix for handling exceptions for unsuccessful token response.

Throw exception for unsuccessful Token Response.

---

io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/DefaultOIDCManager.java
io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/SSOAgentConstants.java
io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/config/FileBasedOIDCConfigProvider.java
io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/config/model/OIDCAgentConfig.java
io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/validators/IDTokenValidator.java

$subject.
Fixes https://github.com/asgardeo/asgardeo-java-oidc-sdk/issues/23.

Set default values for resource retrieval from the JWKS endpoint.

---

io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/SSOAgentConstants.java
io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/request/OIDCRequestResolver.java
io.asgardeo.java.oidc.sdk/src/test/java/io/asgardeo/java/oidc/sdk/request/OIDCRequestResolverTest.java

$subject
Fixes https://github.com/asgardeo/asgardeo-java-oidc-sdk/issues/26.

Add validation to check if the authorization code exists.

---

io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/SSOAgentConstants.java
io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/config/model/OIDCAgentConfig.java
io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/request/OIDCRequestBuilder.java

Note $subject
Resolves https://github.com/asgardeo/asgardeo-java-oidc-sdk/issues/28

Improve SDK to support state param and additional query params passed by webapp

---

io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/DefaultOIDCManager.java
io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/HTTPSessionBasedOIDCProcessor.java
io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/SSOAgentConstants.java
io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/bean/SessionContext.java

Error scenarios were not handled gracefully in the SDK. This fixes that to some extent.
Refers https://github.com/wso2-enterprise/asgardeo-product/issues/3007

Handle errors gracefully

---

io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/request/OIDCRequestResolver.java

Improve the request resolver to handle is_logout request attribute.

---

README.md

$subject
- https://github.com/wso2-enterprise/asgardeo-product/issues/413

Remove IS References

---

pom.xml

$Subject
Resolves: wso2-enterprise/asgardeo-product#8602

Bump log4j version

---

io.asgardeo.java.oidc.sdk/pom.xml
pom.xml

Add scope to org.mock-server dependecies

---

io.asgardeo.java.oidc.sdk/src/test/java/io/asgardeo/java/oidc/sdk/validators/IDTokenValidatorTest.java
pom.xml

> This fixes json-smart DOS vulnerability issue via nimbus version upgrade
> To resolve current DOS vulnerability caused by json-smart comes under nimbus dependency.
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …

Fix json-smart vulnerability issue via nimbus version upgrade

---

io.asgardeo.java.oidc.sdk/src/main/java/io/asgardeo/java/oidc/sdk/HTTPSessionBasedOIDCProcessor.java

Resolves 
- https://github.com/wso2-enterprise/asgardeo-product/issues/9936

Add support for query params sharing

---

README.md

> Use `https://discord.gg/wso2`

Update to customized discord link

---

.azure/asgardeo-java-oidc-sdk-sca-scan.yaml

> Related to the issue https://github.com/wso2-enterprise/asgardeo-product/issues/18060

Integrate FOSSA scan

---

.azure/asgardeo-java-oidc-sdk-sca-scan.yaml
README.md
pom.xml

1. Add Fossa status badges for license scan and security scan
2. Upgrade the sca template to the latest(v1.2.11)
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? N/A
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

Upgrade Fossa templates and features

---

.github/workflows/pr-builder.yml
io.asgardeo.java.oidc.sdk/pom.xml
io.asgardeo.java.oidc.sdk/src/test/java/io/asgardeo/java/oidc/sdk/DefaultOIDCManagerTest.java
io.asgardeo.java.oidc.sdk/src/test/java/io/asgardeo/java/oidc/sdk/HTTPSessionBasedOIDCProcessorTest.java
io.asgardeo.java.oidc.sdk/src/test/java/io/asgardeo/java/oidc/sdk/request/OIDCRequestBuilderTest.java
io.asgardeo.java.oidc.sdk/src/test/java/io/asgardeo/java/oidc/sdk/request/OIDCRequestResolverTest.java
io.asgardeo.java.oidc.sdk/src/test/java/io/asgardeo/java/oidc/sdk/validators/IDTokenValidatorTest.java
pom.xml

Upgrade dependencies for tests.

Upgrade dependencies

---

.azure/asgardeo-java-oidc-sdk-sca-scan.yaml

- $subject
- This is done for temporarily to block the PRs when high and critical vulnerabilities are found
- This will remove after other serverity (Medium and others) are fixed
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” …

Upgrade the SCA scan version to 1.4.14

---

.github/workflows/pr-builder.yml
codecov.yml
io.asgardeo.java.oidc.sdk/pom.xml
pom.xml

This PR adds Codecov and JaCoCo configurations to the repository.

Add Codecov and JaCoCo configurations
